- name: "Launch ui container api_uri: {{ api_uri }}"
  docker_container:
    name: ui
    image: "10.156.207.79:5000/zmora-ui:{{ ui_version }}"
    env:
      API_URI: "{{ api_uri }}"
    ports:
      - "127.0.0.1:3100:80"
    restart: yes
    recreate: yes
    restart_policy: always

