- name: "Launch rabbitmq container"
  docker_container:
    name: rabbitmq
    image: rabbitmq:3.6.11-management
    hostname: rabbitmq
    env:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 256MiB
      RABBITMQ_DEFAULT_USER: "{{ rabbitmq_user }}"
      RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_password }}"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: yes
    restart_policy: always
    networks:
      - name: zmora-net

